# Generated by Django 2.2 on 2022-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220415_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
