# Generated by Django 2.2 on 2022-04-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
