# Generated by Django 2.2 on 2022-05-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('src', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('src', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('src', models.CharField(default='', max_length=300)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('provider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
